# Generated by Django 4.2.5 on 2023-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("addressno", models.AutoField(primary_key=True, serialize=False)),
                ("streetname", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("code", models.IntegerField(blank=True, null=True)),
                ("addresstype", models.IntegerField(blank=True, null=True)),
                (
                    "addresslabel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "address",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cards",
            fields=[
                ("cardno", models.AutoField(primary_key=True, serialize=False)),
                ("cardnumber", models.CharField(max_length=50)),
                ("cardholder", models.CharField(max_length=100)),
                ("expirydate", models.CharField(max_length=10)),
                ("cvv", models.IntegerField()),
            ],
            options={
                "db_table": "cards",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                ("idcart", models.AutoField(primary_key=True, serialize=False)),
                ("cartqty", models.IntegerField(blank=True, null=True)),
                ("cartprice", models.FloatField(blank=True, null=True)),
                ("cartstate", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "cart",
                "db_table_comment": "\t\t\t",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cartitems",
            fields=[
                ("idcartitems", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "cartitems",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customerno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("cellno", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "customers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("iddelivery", models.IntegerField(primary_key=True, serialize=False)),
                ("deliverystatus", models.IntegerField(blank=True, null=True)),
                ("deliverydate", models.DateTimeField(blank=True, null=True)),
                ("shippingdate", models.DateTimeField(blank=True, null=True)),
                ("scheduleddate", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "delivery",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                ("idinvoices", models.AutoField(primary_key=True, serialize=False)),
                ("invoicesamt", models.FloatField(blank=True, null=True)),
                ("invoicesqty", models.IntegerField(blank=True, null=True)),
                ("invoicesdate", models.DateTimeField(blank=True, null=True)),
                ("invoicestype", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "invoices",
                "db_table_comment": "\t",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="productcategory",
            fields=[
                (
                    "idproductcategory",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "productcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "productcategorydescr",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
            ],
            options={
                "db_table": "productcategory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="products",
            fields=[
                ("idproducts", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "productscode",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "productsname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "productsdescription",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("productsprice", models.FloatField(blank=True, null=True)),
                (
                    "productsimg",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
    ]
